#!/bin/bash

set -e

echo "Setting permissions for stacheldrath user..."
chown stacheldrath:stacheldrath -R /home/stacheldrath/.config

echo "Running Ollama installation script..."
curl -fsSL https://ollama.com/install.sh | bash

echo "Running opencode.ai installation script..."
export HOME=/home/stacheldrath/
curl -fsSL https://opencode.ai/install | bash

echo "Starting Ollama and OpenCode services..."
systemctl daemon-reload
systemctl enable --now ollama.service
systemctl enable --now opencode.service

echo "Pulling Ollama model..."
ollama pull deepseek-coder:1.3b

echo "Installation complete!"

exit 0
